# Generated by Django 6.1 on 2026-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('commercial', 'Commercial'), ('healthcare', 'Healthcare'), ('residential', 'Residential'), ('retail', 'Retail'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], max_length=20)),
                ('company', models.CharField(help_text='e.g. ABC Developments', max_length=150)),
                ('description', models.TextField(help_text='e.g. Office fit-out and refurbishment for a 12-storey commercial tower.')),
                ('image', models.ImageField(blank=True, help_text="Optional. Leave empty to show 'No Photo' placeholder.", null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1,2...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
