# Generated by Django 6.1 on 2026-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Case study coming soon', help_text='e.g. Case study coming soon / View Case Study / Completed 2025', max_length=100),
        ),
    ]
