# Generated by Django 5.2.6 on 2026-09-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_alter_project_country",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-year"]},
        ),
    ]