# Generated by Django 5.2.6 on 2026-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_countryimage_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('case_study', 'Case Study Coming Soon')], default='case_study', max_length=30),
        ),
    ]
