# Generated by Django 6.1 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='Number or short text, e.g. 25, 500, 98, 1K (symbols like + or % danna epa)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1,2,3...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
