# Generated by Django 6.1 on 2026-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(choices=[('Years of Excellence', 'Years of Excellence'), ('Projects Completed', 'Projects Completed'), ('Client Retention Rate', 'Client Retention Rate'), ('On-Time Delivery', 'On-Time Delivery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text='Number or short text, e.g. 25, 500, 98, 1K (symbols like + or % dont use)', max_length=20),
        ),
    ]
