# Generated by Django 6.1 on 2026-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g. A free consultation and quotation, always', max_length=200)),
                ('answer', models.TextField(help_text='e.g. Every engagement starts with...')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1,2...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The testimonial text')),
                ('name', models.CharField(default='Client Name', max_length=100)),
                ('role', models.CharField(help_text='e.g. Project Manager', max_length=100)),
                ('company', models.CharField(help_text='e.g. Commercial Project', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1,2...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
