# Generated by Django 6.1 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g. What types of projects do you support?', max_length=255)),
                ('answer', models.TextField(help_text='e.g. We support residential, commercial...')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1,2...)')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'ordering': ['order'],
            },
        ),
    ]
