# Generated by Django 6.1 on 2026-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Countries', 'Countries'), ('Clients', 'Clients')], max_length=100, unique=True)),
                ('value', models.CharField(help_text='Number or short text, e.g. 25, 10K (symbols like + danna epa)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0,1...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
