# Generated by Django 6.1 on 2026-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='e.g. info@lithavi.com (leave empty to show placeholder text)', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='e.g. +94 77 123 4567 (leave empty to show placeholder text)', max_length=30)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
