# Generated by Django 6.1 on 2026-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='location_map_embed_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps EMBED url. Go to Google Maps → search your location → Share → Embed a map → copy the URL inside src="..." (NOT the normal share link). Leave empty to show Sri Lanka country-level map.', max_length=500),
        ),
    ]
